# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

cc_binary(
    name = "kmac_vector_generate",
    srcs = ["kmac_vector_generate.c"],
    deps = [
        "@xkcp//:nist_sp_800_185",
    ],
)
